name: ESP32 Code Validation

on: [push, pull_request]

jobs:

  test-matrix:

    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]
        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    env:
      ESP32CONFIGFILE: --config-file ./Common/Config/arduino-cli.yml
      ESP32EXLIBDIR: ./ESP32/External-libraries/
      ESP32EXLIBBUILDDIR: ${{ env.ESP32EXLIBDIR }}/build
      ESP32INLIBDIR: "./ESP32/Internal-libraries/"

    runs-on: ubuntu-latest

    steps:
    
      - name: Install sketch External libraries
        run: |
          echo ${{ env.ESP32EXLIBDIR }}
          echo ${{ env.ESP32EXLIBBUILDDIR }}