name: ESP32 Code Validation

on: [push, pull_request]

jobs:

  test-matrix:

    strategy:
      matrix:
        arduino-platform: ["esp32:esp32"]
        include:
          - arduino-platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    env:
      ESP32CONFIGFILE: "./Common/Config/arduino-cli.yml"

    runs-on: ubuntu-latest

    steps:
    
      - name: Install sketch External libraries
        run: |
          echo ${{ env.ESP32EXTERNALLIB }}